### ISSUE TITLE
An error occurred.

### ISSUE THREAD

**Issue by Yuhuoo** [pablovela5620/mini-dust3r#1]
I encountered an error on my M1 MacBook Air.

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/test/Desktop/code/mini-dust3r/.pixi/envs/default/lib/python3.11/site-packages/gradio/queueing.py", line 223, in push
    event_queue = self.event_queue_per_concurrency_id[event.concurrency_id]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: '4375055392'
```

**Comment by pablovela5620** [comment]
This sounds like an issue with gradio's concurrency. Can you tell me exactly what command you ran?

**Comment by Yuhuoo** [comment]
I ran the command of '`pixi run gradio-demo`' under the directory of mini-dust3r.

**Comment by pablovela5620** [comment]
can you try running `pixi run rerun-demo --image-dir $PATH-DIR-CONTAINING-IMAGES`. This will narrow down the issue
