### ISSUE TITLE
Nothing display after inference

### ISSUE THREAD

**Issue by cwebber1223** [pablovela5620/mini-dust3r#5]
Dear Pablo,
I tried command: pixi run rerun-demo --image-dir MY_PICTURE_DIR
It seems Global alignement is done, and Inference is done in 100%. But I got this, shown in the below picture, nothing is displayed, nothing is recoreded.
Did I really run it successfully, or not? Did I make some mistake?
Could please help me about this issue?
Thank you very much!

<img width="1756" alt="error" src="https://github.com/user-attachments/assets/9c183e1c-d7ac-4885-a85b-dcf0c73ce9c6">

**Comment by pablovela5620** [comment]
It looks like your instance of rerun didn't correctly initialize, could you try running
`pixi run rerun`?

**Comment by cwebber1223** [comment]
> It looks like your instance of rerun didn't correctly initialize, could you try running `pixi run rerun`?

Thank you very much! I tried "pixi run rerun", but it still has some problem: "RuntimeError: Failed to bind TCP address "0.0.0.0:9876". Another Rerun instance is probably running."

**Comment by cwebber1223** [comment]
> It looks like your instance of rerun didn't correctly initialize, could you try running `pixi run rerun`?

Thank you very much! The display result is OK, now. I do not know what happen to make it OK. I will try more to verify it. Thanks again for your excellent work!
